# Generated by Django 4.0.3 on 2022-05-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('plateId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('imageRef', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vase',
            name='subject',
        ),
        migrations.AddField(
            model_name='vase',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vase',
            name='plateId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vase',
            name='vaseId',
            field=models.AutoField(default='ID ERROR', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vase',
            name='collectionName',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='vase',
            name='publications',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vase',
            name='vaseRef',
            field=models.CharField(default='REF ERROR', max_length=16),
        ),
    ]
