# Generated by Django 4.0.3 on 2022-05-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_plate_remove_vase_subject_vase_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plate',
        ),
    ]
