# Generated by Django 4.0.3 on 2022-05-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vase',
            name='vaseRef',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
