# Generated by Django 4.0.3 on 2022-05-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vase',
            name='vaseId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
