# Generated by Django 4.0.3 on 2022-08-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vase',
            fields=[
                ('vaseId', models.AutoField(primary_key=True, serialize=False)),
                ('vaseRef', models.CharField(blank=True, max_length=16, null=True)),
                ('collectionName', models.CharField(max_length=600)),
                ('previousColl', models.CharField(blank=True, max_length=600, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('provenanceName', models.CharField(blank=True, max_length=600, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('diameter', models.CharField(blank=True, max_length=50, null=True)),
                ('publications', models.CharField(blank=True, max_length=300, null=True)),
                ('plateId', models.CharField(blank=True, max_length=100, null=True)),
                ('fabric', models.CharField(blank=True, max_length=50, null=True)),
                ('technique', models.CharField(blank=True, max_length=50, null=True)),
                ('shapeName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
