# Generated by Django 4.0.6 on 2022-08-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vase',
            old_name='collectionName',
            new_name='collection_name',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='plateId',
            new_name='plate_id',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='previousColl',
            new_name='previous_coll',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='provenanceName',
            new_name='provenance_name',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='shapeName',
            new_name='shape_name',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='vaseId',
            new_name='vase_id',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='vaseRef',
            new_name='vase_ref',
        ),
    ]
