# Generated by Django 4.0.6 on 2022-08-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_collectionname_vase_collection_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vase',
            old_name='collection_name',
            new_name='COLLECTION',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='description',
            new_name='DESCRIPTION',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='diameter',
            new_name='DIAMETER',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='height',
            new_name='HEIGHT',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='vase_id',
            new_name='VASEID',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='vase_ref',
            new_name='VASEREF',
        ),
    ]
