# Generated by Django 4.0.6 on 2022-08-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_collection_name_vase_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vase',
            old_name='plate_id',
            new_name='PLATE',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='publications',
            new_name='PUBLICATION',
        ),
    ]
