# Generated by Django 4.0.6 on 2022-08-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_plate_id_vase_plate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vase',
            old_name='fabric',
            new_name='FABRIC',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='previous_coll',
            new_name='PREVIOUSCOL',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='shape_name',
            new_name='SHAPE',
        ),
        migrations.RenameField(
            model_name='vase',
            old_name='technique',
            new_name='TECHNIQUE',
        ),
    ]
